Counting out
timofey-popov/SPbU-Homeworks pull request #27
Opened 2023-02-07 20:49 UTC by timofey-popov

2023-02-08 08:50 UTC, yurii-litvinov requested changes

2023-02-08 08:50 UTC, yurii-litvinov commented on counting-out/counting-out.c
> +// Добавить значиение в список.
```suggestion
// Добавить значение в список.
```

2023-02-08 08:50 UTC, yurii-litvinov commented on counting-out/counting-out.c
> +    while ((temporaryPointer->value != value) && (temporaryPointer != list->tail)) {
На мой вкус тут скобок больше, чем надо, но делать более явным приоритет операций не запрещается, так что можно и так (но вообще, все знают, что логические "и" и "или" имеют меньший приоритет, чем сравнение, как раз чтобы скобки тут не писать).

2023-02-08 08:50 UTC, yurii-litvinov commented on counting-out/counting-out.h
> +int calculateSuitablePosition(int n, int m, CountingOutErrors* errorCode);
А вот не очень хорошо с точки зрения архитектуры, что потенциально переиспользуемая абстракция "Циклический список" оказалась спрятана в реализации какой-то считалочки. Более правильно тут было бы АТД "Циклический список" сделать модулем, а считалочку — отдельным модулем, или даже реализовать её в main, потому что, кажется, она больше никому в принципе не нужна.

2023-02-08 08:50 UTC, yurii-litvinov commented on counting-out/counting-out.c
> +        deleteFromList(pointer->value, list, &localErrorCode);
А deleteFromList запускает поиск от головы списка, тогда как мы точно знаем позицию, с которой хотим удалить. Это даст квадратичную трудоёмкость вместо линейной, на ровном месте.

2023-02-08 08:50 UTC, yurii-litvinov commented on counting-out/counting-out.h
> +bool insideTests(void);
Если сделать циклический список полноценной абстракцией, то и тесты на него можно будет вынести в отдельный модуль. В общем, одни плюсы.

2023-02-08 19:26 UTC, timofey-popov commented on counting-out/counting-out.c
> +    while ((temporaryPointer->value != value) && (temporaryPointer != list->tail)) {
Мне, скорее, просто кажется, что так удобнее воспринимать визуально, два аккуратных блока в скобках и операнд между ними, а не нагромождение символов. Поэтому в новой попытке я этого не исправлял.

2023-02-09 14:07 UTC, yurii-litvinov approved these changes
Есть только архитектурные замечания, но за архитектуру пока не штрафуют :) Зачтена.

2023-02-09 14:07 UTC, yurii-litvinov commented on counting-out/circularList.h
> +int calculateSuitablePosition(int n, int m, ListErrors* errorCode);
А вот нет, это не часть абстракции "Циклический список", это должно быть в отдельном модуле или main-е. И да, для этого могло потребоваться расширить функциональность списка (например, ввести понятие "Позиция" для того, чтобы можно было как-то работать с deleteElementByPointer извне).

2023-02-09 14:07 UTC, yurii-litvinov commented on counting-out/tests.h
> +bool testForCreateAndDeleteList(void);
А тесты теперь по идее должны быть не прост тесты, а тесты на список и тесты на бизнес-логику

2023-02-26 12:34 UTC, merged